version: "3"

networks:
  grafana:

volumes:
  app_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.16.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana

  loki:
    image: grafana/loki:1.4.1
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana

  promtail:
    image: grafana/promtail:v1.3.0
    volumes:
      - app_data:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - grafana

  grafana:
    image: grafana/grafana:7.0.4
    ports:
      - 3000:3000
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=muge-tutorial-backend-datasource
      - GF_PLUGINS_ENABLE_ALPHA=true
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/plugins:/var/lib/grafana/plugins
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - grafana

  app:
    build: ./app
    ports:
      - 8081:80
    volumes:
      - app_data:/var/log
    networks:
      - grafana

  db:
    image: grafana/tns-db:latest
    ports:
      - 8082:80
    networks:
      - grafana
